# Generated by Django 6.0.5 on 2026-05-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_department_head',
            field=models.BooleanField(default=False),
        ),
    ]
