# Generated by Django 6.0.5 on 2026-05-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_userprofile_is_department_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
