# Generated by Django 6.0.5 on 2026-05-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_complaint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
