# Generated by Django 6.0.5 on 2026-05-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_complaintcategory_complaintsubcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='title',
        ),
    ]
