# Generated by Django 6.0.5 on 2026-05-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_departmenthead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('EMERGENCY', 'Emergency')], default='Medium', max_length=10),
        ),
    ]
