# Generated by Django 6.0.5 on 2026-05-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0013_alter_complaint_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(default='Untitled Complaint', max_length=255),
        ),
    ]
