# Generated by Django 6.0.5 on 2026-05-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0014_alter_complaint_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Complaint Category'),
        ),
    ]
