# Generated by Django 6.0.5 on 2026-05-20 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_category_alter_complaint_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.department'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.complaintsubcategory'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
