# Generated by Django 6.0.5 on 2026-05-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0021_emailotp_userprofile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
