# Generated by Django 6.0.5 on 2026-05-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0023_remove_userprofile_full_name_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='departmenthead',
            name='name',
        ),
        migrations.AddField(
            model_name='complaint',
            name='first_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='departmenthead',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='departmenthead',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
