# Generated by Django 6.0.5 on 2026-05-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0024_remove_complaint_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
