# Generated by Django 6.0.5 on 2026-05-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0025_department_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, default='abc', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
