# Generated by Django 6.0.5 on 2026-06-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0028_complaintfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority_score',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reopened_count',
            field=models.IntegerField(default=0),
        ),
    ]
