# Generated by Django 6.0.5 on 2026-06-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0029_complaint_is_escalated_complaint_priority_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='is_escalated',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='priority_score',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='reopened_count',
        ),
    ]
